[build-system]
requires = ["setuptools>=40.8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "UFCData"
version = "0.7.2"
description = "Obtain UFC data and functions to manipulate it"
requires-python = ">=3.10"

dependencies = [
    "huggingface-hub",
    "pandas",
    "numpy",
    "glicko2",
    "rapidfuzz",
    "matplotlib",
]

[tool.setuptools.packages.find]
include = ["ufcdata*"]
exclude = ["scraper*", "UFCData_backup*"]
